[img src="https://business.livingx.world/images/logo/loisirs/logiciels/office.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="office" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Collaborez gratuitement avec les versions en ligne de Microsoft Word, PowerPoint, Excel et OneNote. Enregistrez les documents, feuilles de calcul et pr&#233;sentations en ligne dans OneDrive. Partagez-les avec d’autres utilisateurs et travaillez dessus simultan&#233;ment.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="#" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] -- [br /]
		[fa name="phone" zoom="2x" /] [a href="#" rel="nofollow"]--[/a] [br /]
		SIRET/VAT [a href="#" rel="nofollow"]--[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: --[ends tags="li" /]
			[begins tags="li" /]Samedi: --[ends tags="li" /]
			[begins tags="li" /]Dimanche: --[ends tags="li" /]
			[begins tags="li" /]Jour férié: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		--
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="office.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="office.com" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="office.com" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[h4 class="text-center"]Particulier[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]famille[ends tags="th" /] 
						[begins tags="th" /]personnel[ends tags="th" /] 
						[begins tags="th" /]famille & etudiant[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="99"' /]€99.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="69"' /]€69.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="149"' /]€149.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="http://go.microsoft.com/fwlink/p/?LinkID=328578" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
						[begins tags="td" /][a href="http://go.microsoft.com/fwlink/p/?LinkID=391343" mdataprop="url"]acheter l'offre[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://go.microsoft.com/fwlink/p/?linkid=2014572" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]		
		[h4 class="text-center"]business[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]business[ends tags="th" /] 
						[begins tags="th" /]premium[ends tags="th" /] 
						[begins tags="th" /]essential[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="8.80"' /]€8.80 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="10.50"' /]€10.50 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="4.20"' /]€4.20 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="http://go.microsoft.com/fwlink/p/?LinkID=404308&culture=fr-FR&country=FR" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
						[begins tags="td" /][a href="http://go.microsoft.com/fwlink/p/?LinkID=510935&culture=fr-FR&country=FR" mdataprop="url"]acheter l'offre[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="http://go.microsoft.com/fwlink/p/?LinkID=510933&culture=fr-FR&country=FR" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-default" /]
			[lxw-badge parent="logiciels" category="bureautique" entreprise="" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-default" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]neutre[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
			[begins tags="dd" /] conforme[ends tags="dd" /]
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /]  	Microsoft IT TLS CA 5 : A[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "office",
		"url": "https://office.com",
		"logo": "https://business.livingx.world/images/logo/loisirs/logiciels/office.png",
		
		"description": "Collaborez gratuitement avec les versions en ligne de Microsoft Word, PowerPoint, Excel et OneNote. Enregistrez les documents, feuilles de calcul et pr&#233;sentations en ligne dans OneDrive. Partagez-les avec d’autres utilisateurs et travaillez dessus simultan&#233;ment.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€"
	}
[ends tags='script' /]