[img src="https://business.livingx.world/images/logo/administration/banque/american-express.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="american express" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Welcome to American Express France, provider of Payment Cards and Privileged Services. Apply for a Card or access your Account.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="FCdKHan99uU" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://americanexpress.com" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 4 Rue Louis Blériot, 92500 Rueil-Malmaison [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33147773000" rel="nofollow"]01 47 77 30 00[/a][br /]
		SIRET/VAT [a href="https://www.societe.com/societe/american-express-carte-france-313536898.html" rel="nofollow"]313 536 898 [/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: 9h00 - 19h00[ends tags="li" /]
			[begins tags="li" /]Saturday: 9h00 - 17h00[ends tags="li" /]
			[begins tags="li" /]Sunday: CLosed[ends tags="li" /]
			[begins tags="li" /]holidays: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167893.80994796427!2d2.026543316406257!3d48.88984229999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66312a7b845f3%3A0x7eb83930fcc5d862!2sAmerican+Express+France!5e0!3m2!1sfr!2sfr!4v1530754938188" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="americanexpress.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="americanexpress.com" /]
		[h3]Your data are[/h3]
		[api-myipms query="americanexpress.com" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[h4 class="text-center"]Card AIR FRANCE KLM[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /] AMERICAN EXPRESS GOLD[ends tags="th" /] 
						[begins tags="th" /] AMERICAN EXPRESS PLATINUM[ends tags="th" /] 
						[begins tags="th" /]Platinum American Express[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Conditions of eligibility: minimum to 35 000€ gross annual revenue [ends tags="td" /] 
						[begins tags="td" /]Conditions of eligibility: minimum to 65 000 € gross annual revenue[ends tags="td" /] 
						[begins tags="td" /]Conditions of eligibility: minimum to 20 000 € gross annual revenue [ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="165"' /]€165.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="570"' /]€570.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="590"' /]€590.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/airfrance-klm-americanexpress-gold/?intlink=FR_CONS_Compare_AF_Gold_EnSavoirPlus" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/airfrance-klm-americanexpress-platinum/?intlink=FR_CONS_Compare_AF_Platinum_EnSavoirPlus" mdataprop="url"]buy offer[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/carte-platinum-americanexpress/?intlink=FR_CONS_Compare_PRY_Platinum_EnSavoirPlus" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]		
		[h4 class="text-center"]Professionnel[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Green[ends tags="th" /] 
						[begins tags="th" /]Gold[ends tags="th" /] 
						[begins tags="th" /]Platinum[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Conditions of eligibility: 20 000 € gross annual revenue[ends tags="td" /] 
						[begins tags="td" /]Conditions of eligibility: minimum to 50 000 € gross annual revenue[ends tags="td" /] 
						[begins tags="td" /]Conditions of eligibility: superior to 80 000 € gross annual revenue[ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="25"' /]€25.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="85"' /]€85.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="399"' /]€399.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-green" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-gold" mdataprop="url"]buy offer[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-platinum" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]trust[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] conform[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] DigiCert SHA2 Extended Validation Server CA : A[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "american express",
		"url": "https://americanexpress.com",
		"logo": "https://business.livingx.world/images/logo/american-express.png",
		"telephone": "+33147773000",
		"description": "Welcome to American Express France, provider of Payment Cards and Privileged Services. Apply for a Card or access your Account.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "4 Rue Louis Blériot",
			"addressLocality": "Rueil-Malmaison",
			"postalCode": "92500",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167893.80994796427!2d2.026543316406257!3d48.88984229999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66312a7b845f3%3A0x7eb83930fcc5d862!2sAmerican+Express+France!5e0!3m2!1sfr!2sfr!4v1530754938188",
		"openingHours": [
			"Mo-Fr 9:00-19:00",
			"Sa 9:00-17:00"
		]
	}
[ends tags='script' /]