[img src="https://business.livingx.world/images/logo/administration/banque/milleis.svg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="milleis" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		To better serve you, Barclays France reinvents itself and becomes Milleis Bank.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="d9Fgj3bTfeQ" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://milleis.fr" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 32 AV GEORGE V 75008 PARIS France [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33155784300" rel="nofollow"]01 55 78 43 00[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/milleis-banque-344748041.html" rel="nofollow"]344 748 041[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: 9h30 - 17h00[ends tags="li" /]
			[begins tags="li" /]Saturday: Closed[ends tags="li" /]
			[begins tags="li" /]Sunday: Closed[ends tags="li" /]
			[begins tags="li" /]holidays: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/us/app/milleis-banque/id1342281774?l=fr&ls=1&mt=8" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/apps/details?id=com.bnet.mobile" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.80727893998!2d2.2886443961784324!3d48.9072858461872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sMilleis+Banque!5e0!3m2!1sfr!2sfr!4v1531020208717" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="milleis.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="milleis.fr" /]
		[h3]Your data are[/h3]
		[api-myipms query="milleis.fr" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[h4 class="text-center"]Particulier[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Type[ends tags="th" /] 
						[begins tags="th" /]Pricing[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Dues immediate card[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="40"' /]€40.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' /]Dues delayed Card[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="45"' /]€45.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Dues maestro Card[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="30"' /]€30.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Retirement[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="00"' /]€00.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Commission intervention[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="8"' /]€8.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Loss and theft insurance[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="26"' /]€26.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Account management[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="15"' /]€15.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/trimestrial[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags="td" /][a href="https://www.milleis.fr/informations-pratiques/tarifs-conditions-et-contrats" mdataprop="url"]subscribe offert[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]		
		[h4 class="text-center"]Professionnel[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Type[ends tags="th" /] 
						[begins tags="th" /]Pricing[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Dues immediate Card mastercard Professionnal executive[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="150"' /]€150.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' /]Dues delayed Card mastercard Professionnal executive[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="165"' /]€165.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Dues immediate Card visa affaire[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="60"' /]€60.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Dues delayed Card affaire [ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="65"' /]€65.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Opening succession[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="100"' /]€100.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]Account management (check ordinaries)[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="15"' /]€15.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/trimestrial[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags="td" /][a href="https://www.milleis.fr/informations-pratiques/tarifs-conditions-et-contrats" mdataprop="url"]subscribe offert[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]doudt[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] GRPD/RGPD missing[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] Entrust Certification Authority - L1K : B (SSL not full)[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "milleis",
		"url": "https://milleis.fr",
		"logo": "https://business.livingx.world/images/logo/milleis.svg",
		"telephone": "+33155784300",
		"description": "To better serve you, Barclays France reinvents itself and becomes Milleis Bank.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "32 AV GEORGE V",
			"addressLocality": "PARIS",
			"postalCode": "75008",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.80727893998!2d2.2886443961784324!3d48.9072858461872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sMilleis+Banque!5e0!3m2!1sfr!2sfr!4v1531020208717",
		"openingHours": [
			"Mo-Fr 9:30-17:00"
		]
	}
[ends tags='script' /]