[img src="https://business.livingx.world/images/logo/administration/banque/bred.jpg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="bred" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		The distance-free bank that combines the best of digital and human. BRED would be fine!
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="pIfqLP8HHR4" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://bred.fr" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] Paris 12éme, 18, quai de la Râpée [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33148986000" rel="nofollow"]01.48.98.60.00[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/bred-banque-populaire-552091795.html" rel="nofollow"]552091795[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday: Closed[ends tags="li" /]
			[begins tags="li" /]thursday to Friday: 9h00 - 18h15[ends tags="li" /]
			[begins tags="li" /]Saturday: 9h00 - 13h00[ends tags="li" /]
			[begins tags="li" /]Sunday: Closed[ends tags="li" /]
			[begins tags="li" /]holidays: Closed[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/fr/developer/bred-banque-populaire/id394121323?mt=8" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/apps/developer?id=Bred" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.8931192752!2d2.2886444350059834!3d48.90718361737622!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sbred+banque+populaire!5e0!3m2!1sfr!2sfr!4v1531897611003" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="bred.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="bred.fr" /]
		[h3]Your data are[/h3]
		[api-myipms query="bred.fr" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]

[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[h4 class="text-center"]Particuliar[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]pricing[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]membership fee card[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="35"' /]à partir de €35.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags="td" /]retraitement[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="1"' /]€1.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Fees Account[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="24"' /]€24.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /]  
						[begins tags="td" /][a href="https://www.bred.fr/resolveuid/816c3d6d2e15400f99f0d4677f90f1b5" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]		
		[h4 class="text-center"]Professionnal[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]pricing[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Fees Account[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="43.64"' /]€43.64 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/years[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /]  
						[begins tags="td" /][a href="https://www.bred.fr/professionnels/tpe/resolveuid/d234d61c6f2d4d5495aba85f88ac5084" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /]  
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]trust[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /]conform[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] DigiCert SHA2 Secure Server CA : B (fixing Authenticated encryption (AEAD) & Forward Secrecy)[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "bred",
		"url": "https://bred.fr",
		"logo": "https://business.livingx.world/images/logo/bred.jpg",
		"telephone": "+33148986000",
		"description": "The distance-free bank that combines the best of digital and human. BRED would be fine!",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "cash",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "18, quai de la Râpée",
			"addressLocality": "Paris",
			"postalCode": "75012",
			"addressCountry": "france"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.8931192752!2d2.2886444350059834!3d48.90718361737622!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sbred+banque+populaire!5e0!3m2!1sfr!2sfr!4v1531897611003",
		"openingHours": [
			"Th-Fr 9:00-18:15",
			"Sa 9:00-13:00"
		]
	}
[ends tags='script' /]