[img src="https://business.livingxworld.com/images/logo/administration/banque/ecopayz.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="ecopayz" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		ecoPayz allows you to make secure online payments and international money transfers. Find out more about ecoPayz payments here.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="IkSB_QHz6-4" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://ecopayz.com" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] Afon Building, Worthing Road, Horsham, West Sussex, RH12 1TL, England [br /]
		[fa name="phone" zoom="2x" /] [a href="#" rel="nofollow"]--[/a] [br /]
		SIRET/VAT [a href="#" rel="nofollow"]900011[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: --[ends tags="li" /]
			[begins tags="li" /]Saturday: --[ends tags="li" /]
			[begins tags="li" /]Sunday: --[ends tags="li" /]
			[begins tags="li" /]holidays: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/fr/app/ecopayz/id842601292?ls=1&mt=8" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/apps/details?id=com.ecoPayz.appID" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2507.590775928447!2d-0.3371100842464217!3d51.06064357956417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4875ea5091aa1449%3A0x614f93fbeaa0e646!2sAfon+Building%2C+5+River+Mead%2C+Worthing+Rd%2C+Horsham+RH12+1TL%2C+Royaume-Uni!5e0!3m2!1sfr!2sfr!4v1531517700582" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]These photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]

[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="ecopayz.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="ecopayz.com" /]
		[h3]Your data are[/h3]
		[api-myipms query="ecopayz.com" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[h4 class="text-center"]Particulier[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]pricing[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Deposit bank wire[ends tags="td" /] 
						[begins tags='td' /]0%-7%[ends tags='td' /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags="td" /]Deposit card[ends tags="td" /] 
						[begins tags='td' /]0%-2.90%[ends tags='td' /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags="td" /]Fees account[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="1.50"' /]€1.50 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Monthly inactive[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /][a href="https://www.ecopayz.com/fr/fees-limits/ecoaccount" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="banque" entreprise="ecopayz" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]trust[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] conform[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] RapidSSL RSA CA 2018 : A[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "ecopayz",
		"url": "https://ecopayz.com",
		"logo": "https://business.livingxworld.com/images/logo/ecopayz.png",
		"description": "ecoPayz allows you to make secure online payments and international money transfers. Find out more about ecoPayz payments here.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "Afon Building, Worthing Road, Horsham, West Sussex, RH12 1TL, England"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2507.590775928447!2d-0.3371100842464217!3d51.06064357956417!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4875ea5091aa1449%3A0x614f93fbeaa0e646!2sAfon+Building%2C+5+River+Mead%2C+Worthing+Rd%2C+Horsham+RH12+1TL%2C+Royaume-Uni!5e0!3m2!1sfr!2sfr!4v1531517700582"
	}
[ends tags='script' /]