[img src="https://business.livingxworld.com/images/logo/administration/banque/lemonway.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="lemonway" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Lemon Way, an authorized payment institution in France, offers a payment solution dedicated to major players in the new economy: crowdfunding platforms, marketplaces, e-commerce sites, sharing economy, mobile payment, kitty payment
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="7e_DJjwppgM" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://lemonway.com" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 14 RUE DE LA BEAUNE 93100 MONTREUIL France [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33148181930" rel="nofollow"]01 48 18 19 30[/a][br /]
		SIRET/VAT [a href="https://www.societe.com/societe/lemon-way-500486915.html" rel="nofollow"]500 486 915[/a] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: --[ends tags="li" /]
			[begins tags="li" /]Saturday: --[ends tags="li" /]
			[begins tags="li" /]Sunday: --[ends tags="li" /]
			[begins tags="li" /]holidays: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.7921955129345!2d2.434028815674507!3d48.86217287928783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66d5d748747fb%3A0x31368b677246975a!2sLemon+Way+SAS!5e0!3m2!1sfr!2sfr!4v1531666269785" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]These photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]

[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="lemonway.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="lemonway.com" /]
		[h3]Your data are[/h3]
		[api-myipms query="lemonway.com" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]method[ends tags="th" /] 
						[begins tags="th" /]fees[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Incoming payment[ends tags="td" /] 
						[begins tags="td" /]Bank card EU[ends tags="td" /]
						[begins tags='td' mdataprop='price' more='content="0.18"' /]1.2%+€00.18 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Incoming payment[ends tags="td" /] 
						[begins tags="td" /]Bank card International[ends tags="td" /]
						[begins tags='td' mdataprop='price' more='content="0.18"' /]2.5%+€00.18 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Outgoing payment[ends tags="td" /] 
						[begins tags="td" /]bank wire EU[ends tags="td" /]
						[begins tags="td" /]free[ends tags="td" /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Outgoing payment[ends tags="td" /] 
						[begins tags="td" /]bank wire International[ends tags="td" /]
						[begins tags='td' mdataprop='price' more='content="15"' /]€15 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /]
						[begins tags="td" /][a href="https://www.lemonway.com/fr/tarifs/" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="banque" entreprise="lemonway" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]trust[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] conform[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] GeoTrust EV SSL CA - G4 : A+[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "lemonway",
		"url": "https://lemonway.com",
		"logo": "https://business.livingxworld.com/images/logo/lemonway.png",
		"telephone": "+33148181930",
		"description": "Lemon Way, an authorized payment institution in France, offers a payment solution dedicated to major players in the new economy: crowdfunding platforms, marketplaces, e-commerce sites, sharing economy, mobile payment, kitty payment",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "14 RUE DE LA BEAUNE",
			"addressLocality": "MONTREUIL",
			"postalCode": "93100",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.7921955129345!2d2.434028815674507!3d48.86217287928783!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66d5d748747fb%3A0x31368b677246975a!2sLemon+Way+SAS!5e0!3m2!1sfr!2sfr!4v1531666269785"
	}
[ends tags='script' /]