
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Bienvenue sur le site d&#039;AG2R LA MONDIALE : 1er groupe de protection sociale. Découvrez nos offres mutuelle santé, prévoyance, épargne et retraite. Trouvez une agence proche de chez vous, contactez-nous, réalisez un devis en ligne.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[dailymotion source="" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://ag2rlamondiale.fr" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 104 BD HAUSSMANN 75008 PARIS [br /]
		[fa name="phone" zoom="2x" /] -- [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/ag2r-reunica-prevoyance-333232270.html" rel="nofollow"]333 232 270 00038[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: 09h00 – 12h30 | 13h30 – 17h30[ends tags="li" /]
			[begins tags="li" /]Samedi: Fermé[ends tags="li" /]
			[begins tags="li" /]Dimanche: Fermé[ends tags="li" /]
			[begins tags="li" /]Jour férié: Fermé[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  28, 32, 80: Saint-Augustin[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  L9: Saint-Augustin[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] accès[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/fr/developer/ag2r-la-mondiale/id400645831" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/search?q=ag2r&hl=fr" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41986.36180589643!2d2.321864860128519!3d48.87446248471679!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fcae61aaaab%3A0x8e04722ac69f28c4!2sAG2R+LA+MONDIALE+-+Agence+Paris+%2F+Haussmann!5e0!3m2!1sfr!2sfr!4v1527916146519" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="ag2rlamondiale.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="ag2rlamondiale.fr" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="ag2rlamondiale.fr" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]Ces photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]


[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[h4 class="text-center"]Particulier[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Velo[ends tags="th" /] 
						[begins tags="th" /]Convention colletif national[ends tags="th" /] 
						[begins tags="th" /]Prévoyance[ends tags="th" /] 
						[begins tags="th" /]Santé[ends tags="th" /] 
						[begins tags="th" /]Retraite[ends tags="th" /] 
						[begins tags="th" /]épargne retraite entreprise[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Engagement à partir 12Mois à 48Mois[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="29.99"' /]à partir de €29.99/Mois [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /]
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.ag2rlamondiale.fr/sante-prevoyance/roulons-velo-decouvrez-le-velo-electrique-reprenez-la-route" mdataprop="url"]souscrire[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprise/conventions-collectives-nationales" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/prevoyance" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/sante" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/retraite" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/epargne-retraite-entreprise" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="assurance-mutuelle" entreprise="ag2rlamondiale" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]Conforme[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] Validé[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] CLASS 2 KEYNECTIS CA : B non sécurisé (corrigé Forward Secrecy, Authenticated encryption (AEAD) cipher suites)[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "ag2r la mondiale",
		"url": "https://ag2rlamondiale.fr",
		"logo": "https://business.livingxworld.com/images/logo/administration/assurance-mutuel/ag2rlamondiale.png",
		"description": "Bienvenue sur le site d&#039;AG2R LA MONDIALE : 1er groupe de protection sociale. Découvrez nos offres mutuelle santé, prévoyance, épargne et retraite. Trouvez une agence proche de chez vous, contactez-nous, réalisez un devis en ligne.",
		"currenciesAccepted": "EUR",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "104 BD HAUSSMANN",
			"addressLocality": "PARIS",
			"postalCode": "75008",
			"addressCountry": "France"
		},
		"hasMap": "uhttps://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41986.36180589643!2d2.321864860128519!3d48.87446248471679!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fcae61aaaab%3A0x8e04722ac69f28c4!2sAG2R+LA+MONDIALE+-+Agence+Paris+%2F+Haussmann!5e0!3m2!1sfr!2sfr!4v1527916146519",
		"openingHours": [
			"Mo-Fr 09:00-17:30"
		]
	}
[ends tags='script' /]