[img src="https://business.livingxworld.com/images/logo/administration/logement/coworking/my-nextdoor.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="nextdoor" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Nextdoor, c’est à la fois une communauté, des lieux, et un état d’esprit. Créateur et opérateur de nouveaux lieux de vie au travail, Nextdoor place l’humain au cœur du business et invite tout à chacun à revoir sa conception du monde du travail pour plus de bienveillance et de productivité.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="TmAQbxVwdmQ" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://my-nextdoor.com" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 3 BD GALLIENI 92130 ISSY LES MOULINEAUX France [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:0173283237" rel="nofollow"]01 73 28 32 37[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/nextdoor-808368856.html" rel="nofollow"]808 368 856[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: 9h00 - 19h00[ends tags="li" /]
			[begins tags="li" /]Samedi: Fermé[ends tags="li" /]
			[begins tags="li" /]Dimanche: Fermé[ends tags="li" /]
			[begins tags="li" /]Jour férié: Fermé[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] [fa name="blind" zoom="2x" /] [fa name="deaf" zoom="2x" /] [fa name="sign-language" zoom="2x" /][ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d83917.81294807825!2d2.253624166862341!3d48.90716771293152!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1snextdoor+coworking!5e0!3m2!1sfr!2sfr!4v1534287149340" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="my-nextdoor.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="my-nextdoor.com" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="my-nextdoor.com" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]Ces photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]


[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Bureaux privatifs[ends tags="th" /] 
						[begins tags="th" /]Hot desks[ends tags="th" /] 
						[begins tags="th" /]Coworking[ends tags="th" /] 
						[begins tags="th" /]salles de réunion[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="552"' /]€552.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mois[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="420"' /]€420.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mois[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="24"' /]€24.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mois[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="18"' /]€18.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mois[ends tags='td' /]  
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.my-nextdoor.com/bureaux-privatifs" mdataprop="url"]acheter l'offre[/a][ends tags="td" /]  
						[begins tags="td" /][a href="https://www.my-nextdoor.com/contacts/" mdataprop="url"]acheter l'offre[/a][ends tags="td" /]  
						[begins tags="td" /][a href="https://www.my-nextdoor.com/coworking" mdataprop="url"]acheter l'offre[/a][ends tags="td" /]  
						[begins tags="td" /][a href="https://www.my-nextdoor.com/salles-de-reunions.html?___store=default" mdataprop="url"]acheter l'offre[/a][ends tags="td" /]  
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-succes" /]
			[lxw-badge parent="logement" category="coworking" entreprise="my-nextdoor" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-succes" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]validé[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] Gandi Standard SSL CA 2 : A+[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "nextdoor",
		"url": "https://my-nextdoor.com",
		"logo": "https://business.livingxworld.com/images/logo/my-nextdoor.png",
		"telephone": "0173283237",
		"description": "Nextdoor, c’est à la fois une communauté, des lieux, et un état d’esprit. Créateur et opérateur de nouveaux lieux de vie au travail, Nextdoor place l’humain au cœur du business et invite tout à chacun à revoir sa conception du monde du travail pour plus de bienveillance et de productivité.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "cash, card",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "3 BD GALLIENI",
			"addressLocality": "ISSY LES MOULINEAUX",
			"postalCode": "92130",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d83917.81294807825!2d2.253624166862341!3d48.90716771293152!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1snextdoor+coworking!5e0!3m2!1sfr!2sfr!4v1534287149340",
		"openingHours": [
			"Mo-Fr 9:00-19:00"
		]
	}
[ends tags='script' /]