[img src="https://business.livingx.world/images/logo/loisirs/sport/keepcool.svg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="keep cool" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Keep Cool, the gym near you. Discover our concept of fitness in more than 170 gyms in France.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="u10MlHs3TsQ" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://keepcool.fr" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] -- [br /]
		[fa name="phone" zoom="2x" /] [a href="#" rel="nofollow"]--[/a] [br /]
		SIRET/VAT [a href="#" rel="nofollow"]--[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: 6h00 - 23h00[ends tags="li" /]
			[begins tags="li" /]Saturday: 6h00 - 23h00[ends tags="li" /]
			[begins tags="li" /]Sunday: 6h00 - 23h00[ends tags="li" /]
			[begins tags="li" /]holidays: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.8931192752!2d2.2886444350059834!3d48.90718361737622!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1skeep+cool!5e0!3m2!1sfr!2sfr!4v1537227665901" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="keepcool.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="keepcool.fr" /]
		[h3]Your data are[/h3]
		[api-myipms query="keepcool.fr" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]Cool[ends tags="th" /] 
						[begins tags="th" /]TwoCool[ends tags="th" /] 
						[begins tags="th" /]TwoCool+[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Folder fees[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="129"' /]€129.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="129"' /]€129.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="129"' /]€129.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]subscribe[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="36.90"' /]€36.90 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mo with engagement[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="41.90"' /]€41.90 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mo with engagement[ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="51.90"' /]€51.90 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mo without engagement[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /][a href="https://vad.keepcool.fr/?c=73&src=www.livingxworld.com&s=2" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://vad.keepcool.fr/?c=73&src=www.livingxworld.com&s=2" mdataprop="url"]buy offer[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://vad.keepcool.fr/?c=73&src=www.livingxworld.com&s=2" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]doudt[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] not conform[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] Amazon : A[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "keep cool",
		"url": "https://keepcool.fr",
		"logo": "https://business.livingx.world/images/logo/loisirs/sport/keepcool.svg",
		"description": "Keep Cool, the gym near you. Discover our concept of fitness in more than 170 gyms in France.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "cash, card",
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d41958.8931192752!2d2.2886444350059834!3d48.90718361737622!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1skeep+cool!5e0!3m2!1sfr!2sfr!4v1537227665901",
		"openingHours": [
			"Mo-Su 6:00-23:00"
		]
	}
[ends tags='script' /]