[img src="https://business.livingxworld.com/images/logo/administration/banque/american-express.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="american-express" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Bienvenue sur American Express France, fournisseur de Cartes de Paiement et de Services Privilégiés. Faites une demande de Carte ou accédez à votre Compte.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="FCdKHan99uU" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://americanexpress.com" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 4 Rue Louis Blériot, 92500 Rueil-Malmaison [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33147773000" rel="nofollow"]01 47 77 30 00[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/american-express-carte-france-313536898.html" rel="nofollow"]313 536 898 [/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: 9h00 - 19h00[ends tags="li" /]
			[begins tags="li" /]Samedi: 9h00 - 17h00[ends tags="li" /]
			[begins tags="li" /]Dimanche: Fermé[ends tags="li" /]
			[begins tags="li" /]Jour férié: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167893.80994796427!2d2.026543316406257!3d48.88984229999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66312a7b845f3%3A0x7eb83930fcc5d862!2sAmerican+Express+France!5e0!3m2!1sfr!2sfr!4v1530754938188" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="americanexpress.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="americanexpress.com" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="americanexpress.com" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]Ces photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]


[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[h4 class="text-center"]Carte AIR FRANCE KLM[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /] AMERICAN EXPRESS GOLD[ends tags="th" /] 
						[begins tags="th" /] AMERICAN EXPRESS PLATINUM[ends tags="th" /] 
						[begins tags="th" /]Platinum American Express[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Conditions d'éligibilité: minimum de 35 000€ de revenus bruts annuels [ends tags="td" /] 
						[begins tags="td" /]Conditions d'éligibilité: minimum de 65 000 € de revenus bruts annuel[ends tags="td" /] 
						[begins tags="td" /]Conditions d'éligibilité: minimum de 20 000 € de revenus bruts annuels [ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="165"' /]€165.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="570"' /]€570.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="590"' /]€590.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/airfrance-klm-americanexpress-gold/?intlink=FR_CONS_Compare_AF_Gold_EnSavoirPlus" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/airfrance-klm-americanexpress-platinum/?intlink=FR_CONS_Compare_AF_Platinum_EnSavoirPlus" mdataprop="url"]buy offer[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://www.americanexpress.com/fr/content/carte-platinum-americanexpress/?intlink=FR_CONS_Compare_PRY_Platinum_EnSavoirPlus" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]		
		[h4 class="text-center"]Professionnel[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Green[ends tags="th" /] 
						[begins tags="th" /]Gold[ends tags="th" /] 
						[begins tags="th" /]Platinum[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Conditions d'éligibilité: 20 000 € de revenus bruts annuels[ends tags="td" /] 
						[begins tags="td" /]Conditions d'éligibilité: minimum de 50 000 € de revenus bruts annuels[ends tags="td" /] 
						[begins tags="td" /]Conditions d'éligibilité: supérieur de 80 000 € de revenus bruts annuels[ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="00"' /]-- [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /]  
						[begins tags='td' mdataprop='price' more='content="85"' /]€85.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="399"' /]€399.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/ans[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-green" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-gold" mdataprop="url"]acheter l'offre[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://business.americanexpress.com/fr/professionnels/cartes-paiement/carte-business-platinum" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="banque" entreprise="americanexpress" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]Validé[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] DigiCert SHA2 Extended Validation Server CA : A[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "american express",
		"url": "https://americanexpress.com",
		"logo": "https://business.livingxworld.com/images/logo/american-express.png",
		"telephone": "+33147773000",
		"description": "Bienvenue sur American Express France, fournisseur de Cartes de Paiement et de Services Privilégiés. Faites une demande de Carte ou accédez à votre Compte.",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "card",
		"priceRange": "€€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "4 Rue Louis Blériot",
			"addressLocality": "Rueil-Malmaison",
			"postalCode": "92500",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167893.80994796427!2d2.026543316406257!3d48.88984229999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66312a7b845f3%3A0x7eb83930fcc5d862!2sAmerican+Express+France!5e0!3m2!1sfr!2sfr!4v1530754938188",
		"openingHours": [
			"Mo-Fr 9:00-19:00",
			"Sa 9:00-17:00"
		]
	}
[ends tags='script' /]