[img src="https://business.livingx.world/images/logo/administration/banque/lcl.jpg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="lcl" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Tous les services LCL Banque et Assurance : gestion de compte, prêt immobilier, crédit auto, assurance, épargne et placements, cartes bancaires, offres étudiants, ¿
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="twreT6ZRNAA" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://lcl.fr" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 18 RUE DE LA REPUBLIQUE 69002 LYON France [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:0892680507" rel="nofollow"]0 892 680 507[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/credit-lyonnais-954509741.html" rel="nofollow"]954 509 741[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Mardi à Samedi: 9h30 - 18h00[ends tags="li" /]
			[begins tags="li" /]Lundi et Dimanche: Fermé[ends tags="li" /]
			[begins tags="li" /]Jour férié: Fermé[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d20979.44489034212!2d2.306154233599324!3d48.907187593367674!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1slcl!5e0!3m2!1sfr!2sfr!4v1532057599933" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="lcl.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="lcl.fr" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="lcl.fr" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[h4 class="text-center"]Professionnel[/h4]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]prix[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Frais tenue compte[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="57"' /]€57.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Carte PRO[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="14"' /]€14.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /][a href="#" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]non sécurisé[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] KEYNECTIS Extended Validation CA : C (corrigé Diffie-Hellman (DH), RC4 cipher, Forward Secrecy et Authenticated encryption (AEAD))[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "lcl",
		"url": "https://lcl.fr",
		"logo": "https://business.livingx.world/images/logo/lcl.jpg",
		"description": "Tous les services LCL Banque et Assurance : gestion de compte, prêt immobilier, crédit auto, assurance, épargne et placements, cartes bancaires, offres étudiants, ¿",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "cash",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "18 RUE DE LA REPUBLIQUE",
			"addressLocality": "LYON",
			"postalCode": "69002",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d20979.44489034212!2d2.306154233599324!3d48.907187593367674!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1slcl!5e0!3m2!1sfr!2sfr!4v1532057599933",
		"openingHours": [
			"Th-Sa 9:30-18:00"
		]
	}
[ends tags='script' /]