[img src="https://business.livingxworld.com/images/logo/administration/banque/psbank.jpg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="psbank" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		psbank
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="9A_z_8oHN1w" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://psbank.com.ph" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 777 Paseo de Roxas corner Sedeño Street, Makati City, 1226 PH [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:6328858219" rel="nofollow"](632) 885-8219[/a]  [br /]
		SIRET/VAT [a href="#" rel="nofollow"]--[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: --[ends tags="li" /]
			[begins tags="li" /]Samedi: --[ends tags="li" /]
			[begins tags="li" /]Dimanche: --[ends tags="li" /]
			[begins tags="li" /]Jour férié: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/ph/app/psbank-mobile-app/id807365364?mt=8" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/apps/details?id=ph.com.psbankonline&hl=en" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d8002271.739519774!2d121.2315764567172!3d11.668932311331446!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1spsbank!5e0!3m2!1sfr!2sfr!4v1531771738590" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="psbank.com.ph" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="psbank.com.ph" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="psbank.com.ph" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]Ces photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]


[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="banque" entreprise="psbank" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]validé[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] Symantec Class 3 EV SSL CA - G3: B (corrigé Diffie-Hellman (DH) )[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "psbank",
		"url": "https://psbank.com.ph",
		"logo": "https://business.livingxworld.com/images/logo/psbank.jpg",
		"telephone": "6328858219",
		"description": "psbank",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "777 Paseo de Roxas corner Sedeño Street",
			"addressLocality": "Makati City",
			"postalCode": "1226",
			"addressCountry": "PH"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d8002271.739519774!2d121.2315764567172!3d11.668932311331446!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1spsbank!5e0!3m2!1sfr!2sfr!4v1531771738590"
	}
[ends tags='script' /]