[img src="https://business.livingx.world/images/logo/administration/banque/toneofirst.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="toneofirst" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		TONEO FIRST Mastercard® est une carte de paiement prépayée et rechargeable sans compte bancaire. Elle permet de sécuriser ses paiements, contrôler ses dépenses, envoyer de l&#039;argent à l&#039;étranger et bien d&#039;autres avantages…
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="vN_MHZB0nr8" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://toneofirst.com" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 16 CITE JOLY 75011 PARIS  [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33170557801" rel="nofollow"]+33 1 70 55 78 01[/a] [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/paycom-809837156.html" rel="nofollow"]809 837 156[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: --[ends tags="li" /]
			[begins tags="li" /]Samedi: --[ends tags="li" /]
			[begins tags="li" /]Dimanche: --[ends tags="li" /]
			[begins tags="li" /]Jour férié: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.7566274660053!2d2.3807240156745437!3d48.86285107928782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66df10ad99d13%3A0xfdf716350e84d3da!2s16+Cit%C3%A9+Joly%2C+75011+Paris!5e0!3m2!1sfr!2sfr!4v1532030651357" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="toneofirst.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="www.toneofirst.com" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="toneofirst.com" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]type[ends tags="th" /] 
						[begins tags="th" /]prix[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Carte[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="15"' /]€15.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Frais[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="5"' /]€5.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /]/Mois[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Retraite[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="2.50"' /]€2.50 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /][a href="#" mdataprop="url"]acheter l'offre[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]douteux[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] non conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] Amazon : A[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "toneofirst",
		"url": "https://toneofirst.com",
		"logo": "https://business.livingx.world/images/logo/toneofirst.png",
		"telephone": "+33170557801",
		"description": "TONEO FIRST Mastercard® est une carte de paiement prépayée et rechargeable sans compte bancaire. Elle permet de sécuriser ses paiements, contrôler ses dépenses, envoyer de l&#039;argent à l&#039;étranger et bien d&#039;autres avantages…",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "cash",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "16 CITE JOLY",
			"addressLocality": "PARIS",
			"postalCode": "75011",
			"addressCountry": "france"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.7566274660053!2d2.3807240156745437!3d48.86285107928782!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66df10ad99d13%3A0xfdf716350e84d3da!2s16+Cit%C3%A9+Joly%2C+75011+Paris!5e0!3m2!1sfr!2sfr!4v1532030651357"
	}
[ends tags='script' /]