[img src="https://business.livingx.world/images/logo/administration/banque/yunacard.jpg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="yunacard" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		YUNA TO GO est une carte prépayée dont le fonctionnement est basé sur l'ajout de crédits. YUNA TO GO vous permet de réaliser vos paiements partout dans le monde dans plus de 35 millions de points de vente acceptant Mastercard®.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://yunacard.com" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] Platz 6 6039 Root D4, Switzerland [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+41800561194" rel="nofollow"]+41 (0) 800 561 194[/a] [br /]
		SIRET/VAT [a href="#" rel="nofollow"]CHE-113.779.646 [/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: xxhxx - xxhxx[ends tags="li" /]
			[begins tags="li" /]Samedi: xxhxx - xxhxx[ends tags="li" /]
			[begins tags="li" /]Dimanche: xxhxx - xxhxx[ends tags="li" /]
			[begins tags="li" /]Jour férié: xxhxx - xxhxx[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/place/D4+Business+Village+Lucerne/@47.103589,8.3717177,17z/data=!4m8!1m2!2m1!1sPlatz+6+6039+Root+D4,+Switzerland!3m4!1s0x478ffe7d85a8ae2f:0xd032f2c65b3817fc!8m2!3d47.104027!4d8.37376" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="yunacard.com" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="www.yunacard.com" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="yunacard.com" /]
	[ends tags="div" /]	
[ends tags="div" /]	



[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[h4 class="text-center"]Particulier[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Frais Carte[ends tags="th" /] 
						[begins tags="th" /]Chargement de la carte (point de vente)[ends tags="th" /] 
						[begins tags="th" /]Taxe Devis étrangère[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="15"' /]15.00 [begins tags="span" mdataprop="priceCurrency" /]CHF[ends tags="span" /][ends tags='td' /]  
						[begins tags='td' /]6%[ends tags='td' /] 
						[begins tags='td' /]2% [ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.yunacard.com/yuna-web/general/fees.xhtml" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://www.yunacard.com/yuna-web/general/fees.xhtml" mdataprop="url"]buy offer[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://www.yunacard.com/yuna-web/general/fees.xhtml" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]Validé[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] Conforme[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /]  	thawte EV SSL CA - G3 : A+[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "yunacard",
		"url": "https://yunacard.com",
		"logo": "https://business.livingx.world/images/logo/yunacard.jpg",
		"telephone": "+41800561194",
		"description": "YUNA TO GO est une carte prépayée dont le fonctionnement est basé sur l'ajout de crédits. YUNA TO GO vous permet de réaliser vos paiements partout dans le monde dans plus de 35 millions de points de vente acceptant Mastercard®.",
		"currenciesAccepted": "CHF",
		"paymentAccepted": "card",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "Platz 6 6039 Root D4",
			"addressCountry": "Switzerland"
		},
		"hasMap": "https://www.google.com/maps/place/D4+Business+Village+Lucerne/@47.103589,8.3717177,17z/data=!4m8!1m2!2m1!1sPlatz+6+6039+Root+D4,+Switzerland!3m4!1s0x478ffe7d85a8ae2f:0xd032f2c65b3817fc!8m2!3d47.104027!4d8.37376"
	}
[ends tags='script' /]