[img src="https://business.livingxworld.com/images/logo/loisirs/sport/pointgym.jpg" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="pointgym" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Présentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Une salle de gym convivialeDes cours de gym diversifiés (gym douce,gym posturale,stretching,gym du dos,culture physique,pilates,abdos,yoga,qi gong,danse classique,street jazz,zumba, du coaching  et un espace massage où vous pouvez vous détendre à tout moment de la journée. Notre équipe sera présente pour vous motiver, vous conseiller et mesurer vos progrès.N'attendez plus! procurez vous un Pass Découverte et tester notre Point Gym
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		L'auteur ne contient pas de vidéo
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]Coordonné[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://pointgym.fr" target="_blank" rel="dofollow"]Site internet[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 211Bis Rue de la Croix Nivert, 75015 Paris [br /]
		[fa name="phone" zoom="2x" /] [a href="tel:+33145337109" rel="nofollow"]01 45 33 71 09[/a] [br /]
		SIRET/VAT [a href="#" rel="nofollow"]--[/a] [br /]
		[h3]Horaires[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Lundi à Vendredi: 9h00 - 21h30[ends tags="li" /]
			[begins tags="li" /]Samedi: 9h00 - 16h00[ends tags="li" /]
			[begins tags="li" /]Dimanche: Fermer[ends tags="li" /]
			[begins tags="li" /]Jour férié: --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  32-62-80
[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  Convention - Boucicaut - Porte de Versailles[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  Desnouettes[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Autres[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] [fa name="blind" zoom="2x" /] [fa name="deaf" zoom="2x" /] [fa name="sign-language" zoom="2x" /][ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Ces logiciels et Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]La carte[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.143005470834!2d2.2877576156735935!3d48.83641087928533!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6706cda1b329b%3A0x3a2d8fe67ee00fb5!2sPoint+Gym!5e0!3m2!1sfr!2sfr!4v1537418387711" /]
		[h4]Êtes-vous intéresser? [begins tags="small"]Cliquer sur la bannière d'affiliation[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]

	
[h2 class="text-center"][begins tags="strong" /]Scanner automatique[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]Priotitaire du site[/h3]
		[whois-domains url="pointgym.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="pointgym.fr" /]
		[h3]Vos données sont:[/h3]
		[api-myipms query="pointgym.fr" /]
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]Ces photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]


[h2 class="text-center"][begins tags="strong" /]Les Tarifs Proposés en TTC (sans promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Type[ends tags="th" /] 
						[begins tags="th" /]Année[ends tags="th" /] 
						[begins tags="th" /]Trimestre[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /]  
						[begins tags="td" /]Club gym[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="805"' /]€805.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="350"' /]€350.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /]  
						[begins tags="td" /]équilibre[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="825"' /]€825.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="360"' /]€360.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /]  
						[begins tags="td" /]Evasion[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="999"' /]€999.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="460"' /]€460.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /]  
						[begins tags="td" /]Club traning[ends tags="td" /] 
						[begins tags='td' mdataprop='price' more='content="600"' /]€600.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
						[begins tags='td' mdataprop='price' more='content="260"' /]€260.00 [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /][a href="https://www.pointgym.fr/tarifs/" mdataprop="url"]buy offer[/a] [ends tags="td" /] 
						[begins tags="td" /][a href="https://www.pointgym.fr/tarifs/" mdataprop="url"]buy offer[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note et avis avec exigence[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge parent="loisirs" category="sport" entreprise="pointgym" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]douteux[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]		
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Contrôle indépendant[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Services chez le client[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Ambiance d'équipe[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Réglementation web[ends tags="dt" /] 
				[begins tags="dd" /] incomplet[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Avis testeur[ends tags="dt" /] 
				[begins tags="dd" /] en cours...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Teste de sécurité web[ends tags="dt" /] 
				[begins tags="dd" /] Let's Encrypt Authority X3 : A[ends tags="dd" /] 
			[ends tags="dl" /] 
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[h2 class="text-center"][begins tags="strong" /]Faire connaître[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]A vous de donner votre opignon: selon ses services clientèles, ses proposition, qualité de la prestation et encore plus.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "pointgym",
		"url": "https://pointgym.fr",
		"logo": "https://business.livingxworld.com/images/logo/loisirs/sport/pointgym.jpg",
		"telephone": "+33145337109",
		"description": "Une salle de gym convivialeDes cours de gym diversifiés (gym douce,gym posturale,stretching,gym du dos,culture physique,pilates,abdos,yoga,qi gong,danse classique,street jazz,zumba, du coaching  et un espace massage où vous pouvez vous détendre à tout moment de la journée. Notre équipe sera présente pour vous motiver, vous conseiller et mesurer vos progrès.N'attendez plus! procurez vous un Pass Découverte et tester notre Point Gym",
		"currenciesAccepted": "EUR",
		"paymentAccepted": "paypal",
		"priceRange": "€€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "211Bis Rue de la Croix Nivert",
			"addressLocality": "Paris",
			"postalCode": "75015",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.143005470834!2d2.2877576156735935!3d48.83641087928533!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6706cda1b329b%3A0x3a2d8fe67ee00fb5!2sPoint+Gym!5e0!3m2!1sfr!2sfr!4v1537418387711",
		"openingHours": [
			"Mo-Fr 9:00-21:30",
			"Sa 9:00-16:30"
		]
	}
[ends tags='script' /]