[img src="https://business.livingxworld.com/images/logo/administration/assurance-mutuel/ag2rlamondiale.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="ag2rlamondiale" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Welcome to the website of AG2R LA MONDIALE: 1st group of social protection. Discover our mutual health, welfare, savings and retirement offers. Find an agency near you, contact us, make an estimate online.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="2ciHKKZOLn8" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://ag2rlamondiale.fr" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 104 BD HAUSSMANN 75008 PARIS [br /]
		[fa name="phone" zoom="2x" /] -- [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/ag2r-reunica-prevoyance-333232270.html" rel="nofollow"]333 232 270 00038[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: 09h00 – 12h30 | 13h30 – 17h30[ends tags="li" /]
			[begins tags="li" /]Saturday: closed[ends tags="li" /]
			[begins tags="li" /]Sunday: closed[ends tags="li" /]
			[begins tags="li" /]holidays: closed[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  28, 32, 80: Saint-Augustin[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  L9: Saint-Augustin[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] access[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/fr/developer/ag2r-la-mondiale/id400645831" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/search?q=ag2r&hl=fr" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41986.36180589643!2d2.321864860128519!3d48.87446248471679!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fcae61aaaab%3A0x8e04722ac69f28c4!2sAG2R+LA+MONDIALE+-+Agence+Paris+%2F+Haussmann!5e0!3m2!1sfr!2sfr!4v1527916146519" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]These photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]

[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="ag2rlamondiale.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="ag2rlamondiale.fr" /]
		[h3]Your data are[/h3]
		[api-myipms query="ag2rlamondiale.fr" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-12" /]	
		[h4 class="text-center"]Particuliar[/h4]
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]bike[ends tags="th" /] 
						[begins tags="th" /]National Collective Agreement[ends tags="th" /] 
						[begins tags="th" /]foresight[ends tags="th" /] 
						[begins tags="th" /]Health[ends tags="th" /] 
						[begins tags="th" /]retirement[ends tags="th" /] 
						[begins tags="th" /]retirement savings business[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]Engagement to beginning 12Month to 48Month[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags='td' mdataprop='price' more='content="29.99"' /]beginning at €29.99/Month [begins tags="span" mdataprop="priceCurrency" /]EUR[ends tags="span" /][ends tags='td' /]
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
						[begins tags='td' /]--[ends tags='td' /] 
					[ends tags="tr" /] 
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.ag2rlamondiale.fr/sante-prevoyance/roulons-velo-decouvrez-le-velo-electrique-reprenez-la-route" mdataprop="url"]subscribe[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprise/conventions-collectives-nationales" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/prevoyance" mdataprop="url"]Asking quote[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/sante" mdataprop="url"]Asking quote[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/retraite" mdataprop="url"]Asking quote[/a][ends tags="td" /] 
						[begins tags="td" /] [a href="https://www.ag2rlamondiale.fr/entreprises/epargne-retraite-entreprise" mdataprop="url"]Asking quote[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	

[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-success" /]
			[lxw-badge parent="administration" category="assurance-mutuelle" entreprise="ag2rlamondiale" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-success" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]Trust[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] Valided[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /] CLASS 2 KEYNECTIS CA : B not secure (fixing Forward Secrecy, Authenticated encryption (AEAD) cipher suites)[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "ag2r la mondiale",
		"url": "https://ag2rlamondiale.fr",
		"logo": "https://business.livingxworld.com/images/logo/administration/assurance-mutuel/ag2rlamondiale.png",
		"description": "Welcome to the website of AG2R LA MONDIALE: 1st group of social protection. Discover our mutual health, welfare, savings and retirement offers. Find an agency near you, contact us, make an estimate online.",
		"currenciesAccepted": "EUR",
		"priceRange": "€€",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "104 BD HAUSSMANN",
			"addressLocality": "PARIS",
			"postalCode": "75008",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d41986.36180589643!2d2.321864860128519!3d48.87446248471679!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fcae61aaaab%3A0x8e04722ac69f28c4!2sAG2R+LA+MONDIALE+-+Agence+Paris+%2F+Haussmann!5e0!3m2!1sfr!2sfr!4v1527916146519",
		"openingHours": [
			"Mo-Fr 09:00-17:30"
		]
	}
[ends tags='script' /]