[img src="https://business.livingxworld.com/images/logo/administration/assurance-mutuel/allianz.png" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="allianz" /]
<hr id="system-readmore" />
[h2 class="text-center"][begins tags="strong" /]Presentation[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[begins tags="strong" /]Description:[ends tags="strong" /][br /]
		Discover our range of insurance products and financial services, make quotes online and get rates.
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[youtube source="L4eNAMKrUf0" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Information[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-4" /]
		[h3]coordinated[/h3]
		[fa name="external-link" zoom="2x" /] [a href="https://allianz.fr" target="_blank" rel="dofollow"]Website[/a] [br /]
		[fa name="map-marker-alt" zoom="2x" /] 1 CRS MICHELET 92800 PUTEAUX  [br /]
		[fa name="phone" zoom="2x" /] -- [br /]
		SIRET/VAT [a href="https://www.societe.com/societe/allianz-france-303265128.html" rel="nofollow"]032 651 280 0023[/a] [br /]
		[h3]Opening schedules[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /]Monday to Friday: 10h00 - 18h00[ends tags="li" /]
			[begins tags="li" /]Saturday: closed[ends tags="li" /]
			[begins tags="li" /]Sunday: closed[ends tags="li" /]
			[begins tags="li" /]holidays: closed[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Transport[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="bus" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="subway" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="train" zoom="2x" /]  --[ends tags="li" /]
			[begins tags="li" /][fa name="car" zoom="2x" /]  --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]Others[/h3] [br /]
		[begins tags="ul" /]
			[begins tags="li" /][fa name="wheelchair" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="broadcast-tower" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="wifi" zoom="2x" /] --[ends tags="li" /]
			[begins tags="li" /][fa name="money-bill" zoom="2x" /] --[ends tags="li" /]
		[ends tags="ul" /]	
		[h3]These software and Apps[/h3]
		[begins tags="ul" /]
			[begins tags="li" /][a href="https://itunes.apple.com/fr/developer/allianz-iard/id358742514" target="_blank"][fa bs="fab" name="apple" zoom="2x" /] Apple[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="windows" zoom="2x" /] Microsoft[/a][ends tags="li" /]
			[begins tags="li" /][a href="https://play.google.com/store/search?q=allianz&hl=fr" target="_blank"][fa bs="fab" name="android" zoom="2x" /] Android[/a][ends tags="li" /]
			[begins tags="li" /][a href="#" target="_blank"][fa bs="fab" name="linux" zoom="2x" /] Linux[/a][ends tags="li" /]
		[ends tags="ul" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-8" /]
		[h3]MAP[/h3]
		[gmaps url="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d20980.531695179394!2d2.3163291941058524!3d48.90459894935273!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sallianz!5e0!3m2!1sfr!2sfr!4v1527929045733" /]
		[h4]Are you interested? [begins tags="small"]Click on the affiliate banner[ends="small" /][/h4] [br /]
		
	[ends tags="div" /]	
[ends tags="div" /]	

[none]
[h2 class="text-center"][begins tags="strong" /]These photo[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt="" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-3" mdatatype="http://schema.org/ImageObject" /]
		[h4][/h4]
		[img src="https://business.livingxworld.com/images/photo/" class="img-fluid rounded mx-auto d-block img-thumbnail border border-info" alt=""" mdataprop="contentUrl" /]
	[ends tags="div" /]	
[ends tags="div" /]	
[/none]

[h2 class="text-center"][begins tags="strong" /]Automatic scanner[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]owner site[/h3]
		[whois-domains url="allianz.fr" /] 
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-12" /]
		[h3]HTTPS: SSL/TLS[/h3]
		[ssllabs domains="allianz.fr" /]
		[h3]Your data are[/h3]
		[api-myipms query="allianz.fr" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]The Prices Proposed in Taxe (without promotion)[ends tags="strong" /] [/h2]
[begins tags="div" class="row" /]
	[begins tags="div" class="col col-12 col-md-6" /]	
		[begins tags="div" class="table-responsive" /] 
			[begins tags="table" class="table table-bordered" mdataprop="offers" mdatatype="http://schema.org/Offer" /] 
				[begins tags="thead" /] 
					[begins tags="tr" /] 
						[begins tags="th" /]Particuliar[ends tags="th" /] 
						[begins tags="th" /]Professionnal[ends tags="th" /] 
					[ends tags="tr" /] 
				[ends tags="thead" /] 
				[begins tags="tbody" /] 
					[begins tags="tr" /] 
						[begins tags="td" /]--[ends tags="td" /] 
						[begins tags="td" /]--[ends tags="td" /] 
					[ends tags="tr" /]
					[begins tags="tr" /] 
						[begins tags="td" /][a href="https://www.allianz.fr/" mdataprop="url"]Demande devis[/a][ends tags="td" /] 
						[begins tags="td" /][a href="https://www.allianz.fr/assurances-professionnels-entreprises/" mdataprop="url"]Asking quote[/a][ends tags="td" /] 
					[ends tags="tr" /]
				[ends tags="tbody" /] 
			[ends tags="table" /] 
		[ends tags="div" /]	
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Note and advice with requirement[ends tags="strong" /] [/h2]
[begins tags="div" class="row text-center" /]
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Badge[/h3]
		[begins tags="div" class="card text-white bg-warning" /]
			[lxw-badge parent="administration" category="assurance-mutuelle" entreprise="allianz" css="card-img-top img-fluid rounded mx-auto d-block img-thumbnail border border-warning" showembed="yes" /]
			[begins tags="div" class="card-body" /]
				[h5 class="card-title"]doubt[/h5]
			[ends tags="div" /]	
		[ends tags="div" /]	
	[ends tags="div" /]	
	[begins tags="div" class="col col-12 col-md-6" /]
		[h3]Independent control[/h3]
		[begins tags="blockquote" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Customer services[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Team atmosphere[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web Regulations[ends tags="dt" /] 
				[begins tags="dd" /] RGPD/GRPD not completed[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Tester reviews[ends tags="dt" /] 
				[begins tags="dd" /] pending ...[ends tags="dd" /] 
			[ends tags="dl" /] 
			[begins tags="dl" /] 
				[begins tags="dt" /]Web security test[ends tags="dt" /] 
				[begins tags="dd" /]  	COMODO RSA Organization Validation Secure Server CA : A+[ends tags="dd" /] 
			[ends tags="dl" /]
		[ends tags="blockquote" /]
	[ends tags="div" /]	
[ends tags="div" /]	


[h2 class="text-center"][begins tags="strong" /]Tell a Friends[ends tags="strong" /] [/h2]
	[begins tags="div" class="row" /] 
		[begins tags="div" class="col-md-12 center-block text-center" /]
			[div class="addthis_inline_share_toolbox" /] 
		[ends tags="div" /] 
	[ends tags="div" /]
 [br /] [br /]
[h6]It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more.[/h6]


[begins tags='script' more='type="application/ld+json"' /] 
	{
		"@context": "http://www.schema.org",
		"@type": "LocalBusiness",
		"name": "allianz",
		"url": "https://allianz.fr",
		"logo": "https://business.livingxworld.com/images/logo/administration/assurance-mutuel/allianz.png",
		"description": "Discover our range of insurance products and financial services, make quotes online and get rates.",
		"currenciesAccepted": "EUR",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "1 CRS MICHELET",
			"addressLocality": "PUTEAUX",
			"postalCode": "92800",
			"addressCountry": "France"
		},
		"hasMap": "https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d20980.531695179394!2d2.3163291941058524!3d48.90459894935273!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sallianz!5e0!3m2!1sfr!2sfr!4v1527929045733",
		
	}
[ends tags='script' /]