<p>[img src="https://business.livingx.world/images/logo/transport/vtc-taxi/kapten.png" alt="kapten" style="display: block; margin-left: auto; margin-right: auto; width: 300px; height: 300px;" /]</p>
<hr id="system-readmore" />
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>Presentation</strong></span></h2>
<p><strong>Description:</strong> Discover Kapten, the VTC app that takes care of its travelers! Your advantages: an exclusive loyalty program, fair prices fixed before the order, the possibility to book your driver in advance and a local and responsive customer service.</p>
<p>[youtube source="uoR8YJPkNqU" /] [begins tags="div" class="row text-center" /] [begins tags="div" class="col-md-12" /] [h3]These software and Apps[/h3]</p>
<p>Apple Store [a href="https://itunes.apple.com/fr/app/kapten/id504597178?mt=8" target="_blank"][fa name="apple" zoom="2x" /][/a] Windows Store [a href="#" target="_blank"][fa name="windows" zoom="2x" /][/a] Google Play [a href="https://play.google.com/store/apps/details?id=fr.chauffeurprive" target="_blank"][fa name="android" zoom="2x" /][/a]</p>
<p>[ends tags="div" /] [ends tags="div" /]</p>
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>Information</strong></span></h2>
<p> </p>
<p>[begins tags="div" class="row" /] [begins tags="div" class="col-xs-12 col-md-4" /] [h3]coordinated[/h3] [fa name="external-link" zoom="2x" /] [a href="//kapten.com" target="_blank"]Site internet[/a] [br /] [fa name="map-marker" zoom="2x" /] 4 PL DU HUIT MAI 1945 92300 LEVALLOIS PERRET France [br /] [fa name="phone" zoom="2x" /] [a href="#"]--[/a] [br /] SIREN: [a href="https://www.societe.com/societe/transopco-france-807978119.html"]807 978 119[/a] [br /] [h3]Horaires[/h3] [br /]</p>
<ul>
<li>24h sur 7 days</li>
</ul>
<p>[h3]Transport[/h3] [br /]</p>
<ul>
<li>Véhicule</li>
<li>Van</li>
<li>mini bus</li>
</ul>
<p>[ends tags="div" /] [begins tags="div" class="col-xs-12 col-md-8" /] [h3]La carte[/h3] [gmaps url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.9951035839026!2d2.295980315675749!3d48.896430479291254!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66f9e13e3645d%3A0xfc678182c8c5f63!2s4+Place+du+8+Mai+1945%2C+92532+Levallois-Perret!5e0!3m2!1sfr!2sfr!4v1556916826640!5m2!1sfr!2sfr" /] [ends tags="div" /] [ends tags="div" /]</p>
<p> </p>
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>Automatic scanner</strong></span></h2>
<p> </p>
<p>[begins tags="div" class="row text-center" /] [begins tags="div" class="col-xs-12 col-md-12" /] [h3]owner site[/h3] [whois-domains url="kapten.com" /] [ends tags="div" /] [begins tags="div" class="col-xs-12 col-md-12" /] [h3]HTTPS: SSL/TLS[/h3] [ssllabs domains="kapten.com" /] [h3]Your data are:[/h3] [api-myipms query="kapten.com" /] [ends tags="div" /] [ends tags="div" /]</p>
<p> </p>
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>The Prices Proposed in Taxe (without promotion)</strong></span></h2>
<p> </p>
<p>[begins tags="div" class="table-responsive" /] [begins tags="table" class="table table-bordered" /] [begins tags="thead" /] [begins tags="tr" /] [begins tags="th" /]immédiate[ends tags="th" /] [begins tags="th" /]à l'avance[ends tags="th" /] [ends tags="tr" /] [ends tags="thead" /] [begins tags="tbody" /] [begins tags="tr" /] [begins tags="td" /]start from 4€/traject [ends tags="td" /] [begins tags="td" /]start from 7€/traject [ends tags="td" /] [ends tags="tr" /] [ends tags="tbody" /] [ends tags="table" /] [ends tags="div" /]</p>
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>Note and advice with requirement</strong></span></h2>
<p> </p>
<p>[begins tags="div" class="row text-center" /] [begins tags="div" class="col-xs-12 col-md-6" /] [h3]Badge[/h3] [lxw-badge showembed="yes" /] [begins tags="dl" class="dl-horizontal" /] [begins tags="dt" /]Tester reviews (by Administrateur)[ends tags="dt" /] [begins tags="dd" /] test not performed by Administrator current ...[ends tags="dd" /] [ends tags="dl" /] [begins tags="dl" class="dl-horizontal" /] [begins tags="dt" /]Web security test[ends tags="dt" /] [begins tags="dd" /]  	Gandi Standard SSL CA 2  : A [ends tags="dd" /] [ends tags="dl" /] [ends tags="div" /] [begins tags="div" class="col-xs-12 col-md-6" /] [h3]Independent control[/h3] [begins tags="blockquote" /] [begins tags="dl" class="dl-horizontal" /] [begins tags="dt" /]Customer services[ends tags="dt" /] [begins tags="dd" /]Control not performed by Administrator current ...[ends tags="dd" /] [ends tags="dl" /] [begins tags="dl" class="dl-horizontal" /] [begins tags="dt" /]Team atmosphere[ends tags="dt" /] [begins tags="dd" /]Control not performed by Administrator current ...[ends tags="dd" /] [ends tags="dl" /] [begins tags="dl" class="dl-horizontal" /] [begins tags="dt" /]Web Regulations[ends tags="dt" /] [begins tags="dd" /][fa name="check" /] complete[ends tags="dd" /] [ends tags="dl" /] [ends tags="blockquote" /] [ends tags="div" /] [ends tags="div" /]</p>
<p> </p>
<h2 style="text-align: center;"><span style="text-decoration: underline;"><strong>Tell a Friends</strong></span></h2>
<p> </p>
<p>[begins tags="div" class="row" /] [begins tags="div" class="col-md-12 center-block text-center" /] [div class="addthis_inline_share_toolbox" /] [ends tags="div" /] [ends tags="div" /] [br /] [br /] It is up to you to give your opinion: according to its customer service, its proposals, quality of the service and more. [begins tags='script' more='type="application/ld+json"' /] { "@context": "http://www.schema.org", "@type": "LocalBusiness", "name": "kapten", "url": "https://kapten.com", "logo": "https://business.livingx.world/images/logo/transport/vtc-taxi/kapten.png", "telephone": "3607", "description": "Discover Kapten, the VTC app that takes care of its travelers! Your advantages: an exclusive loyalty program, fair prices fixed before the order, the possibility to book your driver in advance and a local and responsive customer service.", "currenciesAccepted": "EUR", "paymentAccepted": "card", "priceRange": "€", "address": { "@type": "PostalAddress", "streetAddress": "4 PL DU HUIT MAI 1945", "addressLocality": "LEVALLOIS PERRET", "postalCode": "92300", "addressCountry": "FRANCE" }, "hasMap": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2622.9951035839026!2d2.295980315675749!3d48.896430479291254!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66f9e13e3645d%3A0xfc678182c8c5f63!2s4+Place+du+8+Mai+1945%2C+92532+Levallois-Perret!5e0!3m2!1sfr!2sfr!4v1556916826640!5m2!1sfr!2sfr", "review": { "@type": "Review", "author": "Alexon Balangue", "dateCreated": "2014-06-12", "datePublished": "2014-06-12", "dateModified": "2017-08-25", "inLanguage": "english", "name": "kapten", "reviewBody": "", "reviewRating": { "@type": "Rating", "bestRating": "5", "ratingValue": "2", "worstRating": "1" }, "CopyrightHolder": "LivingxWorld", "creator": "Alexon Balangue" } } [ends tags="script" /]</p>